# Generated by Django 2.1.2 on 2018-12-30 22:03

import conference.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konferencija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sekcije', models.CharField(max_length=120)),
                ('form', models.CharField(default=None, max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('chairman', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=conference.models.user_directory_path)),
                ('title', models.CharField(max_length=120)),
                ('approved', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sekcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('konferencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Konferencija')),
            ],
        ),
        migrations.CreateModel(
            name='User_Sekcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzent_not_approved', models.BooleanField(default=False)),
                ('recenzent_approved', models.BooleanField(default=False)),
                ('questions', models.CharField(default=None, max_length=1000)),
                ('sekcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Sekcija')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='radovi',
            name='user_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.User_Sekcija'),
        ),
        migrations.AlterUniqueTogether(
            name='user_sekcija',
            unique_together={('sekcija', 'user')},
        ),
    ]
