# Generated by Django 2.1.2 on 2018-12-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radovi',
            name='authors',
            field=models.CharField(default='filip@fer.hr', max_length=120),
            preserve_default=False,
        ),
    ]
