# Generated by Django 2.1.2 on 2019-01-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_radovi_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferencija',
            name='description',
            field=models.CharField(default='Genetics and Molecular Biology seek to understand how the molecules that make up cells determine the behaviour of living things. Molecular biology is the study of biology at a molecular level. The field overlaps with other areas of biology and chemistry, particularly genetics and biochemistry. Molecular biology chiefly concerns itself with understanding the interactions between the various systems of a cell, including the interrelationship of DNA, RNA and protein synthesis and learning how these interactions are regulated. Genetics is the study of genes, inheritance and variation in living organisms. It is commonly considered a field of biology which intersects frequently with many of life sciences and is strongly related with the study of information systems. While the average height of the two corn stalks may be heritably determined to be equal, the one in the arid climate only grows to half the height of the one in the temperate weather, due to lack of nutrients and water in its environment. Genetics conferences and Molecular biology conferences creates a plat form to all young scientists, Researchers to discuss pros and cons under a single roof.', max_length=4000),
            preserve_default=False,
        ),
    ]
