# Generated by Django 2.1.2 on 2018-11-05 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20181105_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='chairman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to=settings.AUTH_USER_MODEL),
        ),
    ]
