# Generated by Django 2.1.2 on 2019-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_konferencija_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferencija',
            name='summary',
            field=models.CharField(default='This is a conference about biology', max_length=2000),
            preserve_default=False,
        ),
    ]
