# Generated by Django 2.1.2 on 2019-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_konferencija_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferencija',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
